# Generated by Django 4.2.7 on 2023-12-01 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proffession', models.CharField(max_length=50)),
                ('edu_level', models.CharField(choices=[('Elementary', 'Elementary'), ('Highschool', 'Highschool'), ('Gradudate', 'Gradudate'), ('Masters', 'Masters')], max_length=20)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
