# Generated by Django 4.2.7 on 2023-11-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_remove_course_resources_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
