# Generated by Django 4.2.7 on 2023-11-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_topic_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, upload_to='resource_files/'),
        ),
    ]
