# Generated by Django 4.2.7 on 2023-11-28 18:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_resource_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='descriptions',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(max_length=10000),
        ),
    ]
