# Generated by Django 4.2.7 on 2023-12-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0007_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
